// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHddIhGA3_KIdfQR3QqHjE98QvETStsPE',
    appId: '1:437003498757:web:be22e253e098913bdb336c',
    messagingSenderId: '437003498757',
    projectId: 'archroma-approve',
    authDomain: 'archroma-approve.firebaseapp.com',
    storageBucket: 'archroma-approve.firebasestorage.app',
    measurementId: 'G-98C9K0N6TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySW1VQOVtmie-CySkl9ojnxUaNO_gVJk',
    appId: '1:437003498757:android:88bb0dc07745d046db336c',
    messagingSenderId: '437003498757',
    projectId: 'archroma-approve',
    storageBucket: 'archroma-approve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo0uF-y6FFPErxTmupzVSK9lRCJ0NxCXs',
    appId: '1:437003498757:ios:d7da2a4e7f27a4a9db336c',
    messagingSenderId: '437003498757',
    projectId: 'archroma-approve',
    storageBucket: 'archroma-approve.firebasestorage.app',
    iosBundleId: 'com.example.archApprove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo0uF-y6FFPErxTmupzVSK9lRCJ0NxCXs',
    appId: '1:437003498757:ios:d7da2a4e7f27a4a9db336c',
    messagingSenderId: '437003498757',
    projectId: 'archroma-approve',
    storageBucket: 'archroma-approve.firebasestorage.app',
    iosBundleId: 'com.example.archApprove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHddIhGA3_KIdfQR3QqHjE98QvETStsPE',
    appId: '1:437003498757:web:b6bc8668ea34cfbadb336c',
    messagingSenderId: '437003498757',
    projectId: 'archroma-approve',
    authDomain: 'archroma-approve.firebaseapp.com',
    storageBucket: 'archroma-approve.firebasestorage.app',
    measurementId: 'G-P70QRXLE4F',
  );
}
